export const GAME_BROWSER_EVENTS = Object.freeze({
    CONSOLE_CARDS: 'bsg:console-cards',
    CONSOLE_TURN_TIMER: 'bsg:console-turn-timer',
    CONSOLE_BUST: 'bsg:console-bust',
    CONSOLE_WIN: 'bsg:console-win',
    EMOJI_SENT: 'bsg:emoji-sent',
    GUEST_TUTORIAL_UPDATE: 'guest-tutorial:update',
    NAVIGATE: 'bsg:navigate',
    PROFILE_REFRESH: 'bsg:profile-refresh',
    SIDE_BET_CONFIG: 'bsg:side-bet-config',
    SIDE_BET_PAYOUT: 'bsg:side-bet-payout',
    SIDE_BET_WINDOW: 'bsg:side-bet-window',
    SIDE_BETS_CHANGE: 'bsg:side-bets-change',
    SIDE_BETS_SERVER_STATE: 'bsg:side-bets-server-state',
    SOUND_STATE: 'bsg:sound-state',
    SOUND_TOGGLE: 'bsg:sound-toggle',
});
