FROM node:22-alpine AS builder

WORKDIR /app

ARG REACT_APP_API_ENDPOINT
ARG REACT_APP_ENVIRONMENT=1
ARG REACT_APP_STRIPE_PUBLISHABLE_KEY

ENV REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
ENV REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY

COPY package*.json ./
RUN npm install

COPY . ./
RUN ./node_modules/.bin/react-scripts build

FROM nginx:alpine

COPY deploy/nginx-spa.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
