services:
  game-backend:
    build: .
    container_name: game-backend
    command: npm start
    env_file:
      - .env
    environment:
      DB_URL: mongodb+srv://admin:Ram%401999@bigslick.zojd8mn.mongodb.net/holdem
      PORT: 4000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BASE_API_PATH: http://game-backend:4000/api/v1
      FRONTEND_URL: http://game-frontend:3000
    depends_on:
      - redis
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: game-backend-redis
    restart: unless-stopped
