services:
  web:
    build: .
    container_name: poker-jack-admin-container
    command: node index.js
    env_file:
      - .env
    environment:
      DB_URL: mongodb+srv://admin:Ram%401999@bigslick.zojd8mn.mongodb.net/holdem
      PORT: 3051
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BASE_URL: http://web:3051
      BASE_API_PATH: http://web:3051/api/v1
      FRONTEND_URL: http://admin-frontend:3000
    volumes:
      - .:/app
    ports:
      - '3051:3051'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: admin-backend-redis
    restart: unless-stopped
